

spring:
  profiles:
    include:
      - info
  datasource:
    url: jdbc:mysql://localhost/ecomerce
    username: root
    password: mysql

  jackson:
    serialization:
      fail-on-empty-beans: false

  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update
      enable_lazy_load_no_trans:  true

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost/escromax-ecomerce
    username: root
    password: mysql
---
spring:
  profiles: prod
  datasource:
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
---